### ISSUE TITLE
Linux build guide [Ubuntu 16.04]

### ISSUE THREAD

**Issue by RTheren** [pjasicek/CaptainClaw#1]
Hello,

I've managed to successfully build a Linux version of your project:

**Prerequisites for Ubuntu 16.04:**
`sudo apt install libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-gfx-dev libtinyxml-dev` 

Now for the compilation itself:

- git clone https://github.com/pjasicek/CaptainClaw.git
- cd CaptainClaw
- mkdir build
- cd build
- cmake ..
- make -j4
- cd ../Build_Release
- ./captainclaw

[Screenshot of working build](
http://imgur.com/a/RYQel)

**Comment by pjasicek** [comment]
Hi, thanks for trying it out !

The README is a bit outdated, we will soon update the linux section.

**Comment by RTheren** [comment]
I've noticed ;)

Diky za (nie uplne) ozivene detstvo :)
