### ISSUE TITLE
 Sprites at the end of climbing the stairs

### ISSUE THREAD

**Issue by italozaina** [pjasicek/CaptainClaw#102]
It's a different sprite than climbing, as if it had been leaning on the top of the ladder

**Comment by pjasicek** [comment]
https://github.com/pjasicek/CaptainClaw/commit/2af811423232c96840c8a0f264a85d872197e411

This was honestly the best implementation I could come up with. Monolith did not even make animation file for this feature so I had to somehow code it. It is not by far as smooth as it is in original game but I guess it is fine.

There is a glitch when already climbing up / down and then switching direction - the animation transition is not smooth

**Comment by pjasicek** [comment]
With https://github.com/pjasicek/CaptainClaw/commit/df944f420dc0ea2d67547427af62c06219b5ae87 it is now more smooth when climbing down from top.
