### ISSUE TITLE
Boss 2 OP

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#104]
LaRaux parry is too OP :laughing:

**Comment by pjasicek** [comment]
Parry is done my way - he has I think 33% chance to parry Claw's attack and once he parries and Claw attacks him while he is still in parry animation he will parry again. So Claw has to wait a bit before attacking so that parry state wears off.

**Comment by pjasicek** [comment]
Closing this for now. If more of you guys consider this a problem, make another issue and I will reconsider.
