### ISSUE TITLE
Water splash sound

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#105]
In original Claw game when Claw kills an enemy after few moment a splash water sound is played

**Comment by pjasicek** [comment]
I dont know what you mean. Could you maybe send a link from some original CaptainClaw lets play with a timestamp where this can be seen/heard ?

**Comment by cipiricus** [comment]
https://youtu.be/PpltxMl5IFQ?t=59s

**Comment by pjasicek** [comment]
heh, I have never ever noticed this

**Comment by pjasicek** [comment]
Fixed with https://github.com/pjasicek/CaptainClaw/commit/c62020fa7a249fbe0d7c495194ce692a34afd6bf
