### ISSUE TITLE
After level ends, there should be score screen

### ISSUE THREAD

**Issue by pjasicek** [pjasicek/CaptainClaw#15]
After any level ends, either by killing boss or picking a map piece, screen with picked up treasures should be presented. After this screen is left (by pressing Enter or Escape), next level should be loaded.

**Comment by pjasicek** [comment]
- All required resources are located in **/STATES/BOOTY/***
- Background screens for particular levels are in **/STATES/BOOTY/SCREENS/***
- Images (treasure pickups, text...) are in **/STATES/BOOTY/IMAGES/***

**Comment by pjasicek** [comment]
I made a great deal of progress today with this, but I came across an obstacle that I probably will not be able to easily pass:

http://s7.postimg.org/xitoouiez/screenshot_1.png

This happens because there is not a SINGLE palette which suits the colors in /STATE/BOOTY/*.PID files. Atleast somewhat good thing is that I can reuse stuff from /GAME/IMAGES/TREASURES/* which fit to any of the level's color palette and atleast the background images are in PCX format.

What this means is that the score screen will not be exactly like in original game, since I do not have the assets.

I am also thinking how is this possible. The only solution I can think of is that they just hardcoded the color palette in their code (it has 768 bytes).

**Comment by pjasicek** [comment]
After a bit of investigation, these PID files are encoded (CLAW sometimes uses RLE encoding for PIDs), but I have this covered already in libwap (CLAW's frames are also encoded and they display just fine). So I guess the problem is not there.

I will just think of a solution of how to best replace the invalid images.

**Comment by pjasicek** [comment]
I went down the grueling way and that is reconstructing the palette from decoding the compressed images. Workflow is as follows: 

- Launch original game, get a screenshot of score screen, print screen, move it to photoshop, select exactly the PID file and put it in new photoshop tab.
- Decode and save the original PID file with each byte pointing to palette color index and its pixel coordinates
- Get all unique palette indexes
- For each unique palette color index, look at photoshop image X-Y coordinate, get the RGB color and save it to binary array

Now I have about 40 colors, 215 to go..

**Comment by pjasicek** [comment]
Its slowly coming together, wrote a piece of program to do bunch of stuff for me

http://s7.postimg.org/l235jbgl7/screenshot_3.png

**Comment by pjasicek** [comment]
Almost whole palette is reconstructed (around 25 colors are still missing) but I do not need them at the moment:

http://s7.postimg.org/o0ihvzhrv/screenshot_5.png

**Comment by pjasicek** [comment]
Score screen (for level 1) is implemented with f714339800bd1c4291baa62b6a648e3e51f6fbdc as closely to original game as possible.

When you are in score screen, you can skip intro -> skip loading treasures -> load next level by pressing enter/spacebar/escape

I would very much appreciate if someone could test this on Linux machine.

**Comment by denispapec** [comment]
Works on Arch Linux with commit https://github.com/pjasicek/CaptainClaw/commit/f714339800bd1c4291baa62b6a648e3e51f6fbdc, no issues there.
