### ISSUE TITLE
Level 2 - Cannon towers have no logic

### ISSUE THREAD

**Issue by pjasicek** [pjasicek/CaptainClaw#19]
Cannon towers in Level 2 have no logic - they do not do anything. They should fire a cannonball when Claw comes to its agro range.

**Comment by cipiricus** [comment]
will be possible sometime?

**Comment by pjasicek** [comment]
Of course :) Implementing this one is especially easy. This, and lots of other bugs / missing features will be implemented in following days.

**Comment by cipiricus** [comment]
if will this bugs will be fixed I will try to make first build for Raspberry Pi :)

**Comment by pjasicek** [comment]
We already compiled it for Raspberry, but the performance was awful - it had I think 5 FPS with 800x600 resolution. Raspberry has really slow GPU for these purposes :)

**Comment by pjasicek** [comment]
Tried to implement this as Enemy with ranged component only but soon I ralized that this was not clean design. I will make a new component for this, something as SpawnerComponent combined with TriggerComponent for handling Claw entering its attack area.

It will be most likely done today or latest tomorrow.

**Comment by cipiricus** [comment]
I'm thinking, in level 3 and 4 there is some plants it can catapult Claw very high, the code from this "plants" can be applied for steam pipes from level 6 or springs from level 9 and 10?

**Comment by pjasicek** [comment]
Yes, exactly. The logic for these things will be exactly the same, I will just swap graphics.

**Comment by cipiricus** [comment]
And about cannon logics, I'm thinking will be can applied very well for arrows from level 9, 10, 13 and for flames from level 14

**Comment by pjasicek** [comment]
Yes, it will be applied for every object whichs spawns a projectile.

**Comment by cipiricus** [comment]
cool :) i will try now :+1:

**Comment by pjasicek** [comment]
in https://github.com/pjasicek/CaptainClaw/commit/a8644b5e90dc2655cf1591a99ed598ccbe6bf469 I have just added the second tower cannon (facing right)

**Comment by pjasicek** [comment]
Since https://github.com/pjasicek/CaptainClaw/commit/9b2afb9ea8e594de96360eb81b45493743c9ca80 tower cannons have appropriate fire sounds
