### ISSUE TITLE
Not building on Linux anymore [Ubuntu 16.04]

### ISSUE THREAD

**Issue by RTheren** [pjasicek/CaptainClaw#2]
Hello, I am getting compilation errors during building:
It started happening 2 merges ago.

> 
> [ 84%] Building CXX object CMakeFiles/captainclaw.dir/CaptainClaw/Engine/Resource/Loaders/AniLoader.cpp.o
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp: In member function ‘bool ZipFile::Init(const string&)’:
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp:122:48: error: ‘fopen_s’ was not declared in this scope
>      fopen_s(&m_pFile, resFileName.c_str(), "rb");
>                                                 ^
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp:172:27: error: ‘_MAX_PATH’ was not declared in this scope
>              char fileName[_MAX_PATH];
>                            ^
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp:173:20: error: ‘fileName’ was not declared in this scope
>              memcpy(fileName, pfh, fh.fnameLen);
>                     ^
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp:175:42: error: ‘_strlwr_s’ was not declared in this scope
>              _strlwr_s(fileName, _MAX_PATH);
>                                           ^
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp: In member function ‘std::__cxx11::string ZipFile::GetFilename(int) const’:
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp:270:22: error: ‘_MAX_PATH’ was not declared in this scope
>          char pszDest[_MAX_PATH];
>                       ^
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp:271:16: error: ‘pszDest’ was not declared in this scope
>          memcpy(pszDest, m_papDir[i]->GetName(), m_papDir[i]->fnameLen);
>                 ^
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp: In member function ‘bool ZipFile::Init(const string&)’:
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp:133:39: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
>      fread(&dh, sizeof(dh), 1, m_pFile);
>                                        ^
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp:147:46: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
>      fread(m_pDirData, dh.dirSize, 1, m_pFile);
>                                               ^
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp: In member function ‘bool ZipFile::ReadFile(int, void*)’:
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp:310:37: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
>      fread(&h, sizeof(h), 1, m_pFile);
>                                      ^
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp:320:41: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
>          fread(pBuf, h.cSize, 1, m_pFile);
>                                          ^
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp:332:39: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
>      fread(pcData, h.cSize, 1, m_pFile);
>                                        ^
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp: In member function ‘bool ZipFile::ReadLargeFile(int, void*, void (*)(int, bool&))’:
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp:384:37: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
>      fread(&h, sizeof(h), 1, m_pFile);
>                                      ^
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp:394:41: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
>          fread(pBuf, h.cSize, 1, m_pFile);
>                                          ^
> /home/rtheren/Games/Claw/CaptainClaw/CaptainClaw/Engine/Resource/ZipFile.cpp:406:39: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
>      fread(pcData, h.cSize, 1, m_pFile);
>                                        ^
> CMakeFiles/captainclaw.dir/build.make:1598: recipe for target 'CMakeFiles/captainclaw.dir/CaptainClaw/Engine/Resource/ZipFile.cpp.o' failed
> make[2]: *** [CMakeFiles/captainclaw.dir/CaptainClaw/Engine/Resource/ZipFile.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/captainclaw.dir/all' failed
> make[1]: *** [CMakeFiles/captainclaw.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by pjasicek** [comment]
Yea, windows specific third party code. I'll fix it in a couple of hours, thanks for pointing this out.

**Comment by pjasicek** [comment]
Fixed with #87ef334da9dc2d07ad60fcfe2393ed3990594ad8
