### ISSUE TITLE
Invisibility powerup and Iron Heart powerup

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#21]
Hi, is there a chance to implement that? TY :) https://cloud.orange.ro/share/6e3d41b1f5ee88a81cff48268b71b3ab09daa7984b474901

**Comment by pjasicek** [comment]
Yea, sure, it will be implemented in near future :) thanks for the report

**Comment by pjasicek** [comment]
Invisibility implemented with https://github.com/pjasicek/CaptainClaw/commit/da62ca2821bc39c7fbea899fcc833cedd203bf20

Invisibility can also be acquired by writing "invis" into the console (";")

At the moment I am not quite sure how to implement the invincibility coloring scheme.

**Comment by pjasicek** [comment]
Invincible powerup implemented with https://github.com/pjasicek/CaptainClaw/commit/778ff46c4c83b2f65da756b380b1ef571ff49823

Invincibility can also be accessed via console by writing "invlr" or "invincible" into the console (";")

For not I just changed Claw's color mod to indicate the invincibility. Closing.
