### ISSUE TITLE
No background music during play

### ISSUE THREAD

**Issue by denispapec** [pjasicek/CaptainClaw#22]
![screenshot-2017-05-05_21 23 03](https://cloud.githubusercontent.com/assets/5442891/25763336/79b9bd60-31da-11e7-8b7e-4a631022803e.png)
On Arch Linux, with installed and configured [timidity](https://wiki.archlinux.org/index.php/timidity) (as suggested on #9 ) there is no audio output for background music.
I've tested timidity functionality with simple midi track file, and that seems to work.

**Comment by pjasicek** [comment]
I just tried it on my 3 years old Fedora machine and I had the same problem.

I compiled without a problem, then I ran the game, loaded a level, and had this error:

> ERROR: [SetupPlayMusicThread] Mix_LoadMUS_RW: /etc/timidity/freepats.cfg: No such file or directory

I then installed timidity++ package from repo and then I had to manually install timidity-patch-freepats (downloaded RPM from https://mageia.pkgs.org/5/mageia-core-release-x86_64/timidity-patch-freepats-20060219-19.mga5.noarch.rpm.html)

Then the background music worked, though the sound is NOT the same as on Windows (probably different instrument synthesizers or stuff like that, don't know).

Also when I only installed timidity-devel package (not timidity++) it worked without the need to manually install the freepats.

**Comment by pjasicek** [comment]
I am thinking of just converting all the .XMI (well, MIDI) tracks to MP3 which is easily digestable by SDL_Mixer and it does not need special synthetizers as far as I know.

**Comment by denispapec** [comment]
I've reinstalled both timidity++ and [timidity-freepats](https://www.archlinux.org/packages/community/any/timidity-freepats/), reapplied patches and now seems to work!

**Comment by pjasicek** [comment]
Great ! How is the sound, is it okay ?

**Comment by denispapec** [comment]
When i set sounds and music to same audio level in options, on level 1 music is a bit quieter than sounds, but on level 2, music it quieter a lot.

**Comment by pjasicek** [comment]
Yea, I know about that, it is similiar in original game. You have to manually tweak the music level either in config.xml or from the menu audio options.

**Comment by cipiricus** [comment]
Interesting, I will try today on my Ubuntu 16.04.2 with timidity

**Comment by loblik** [comment]
Debian (ubuntu probably also) provides libsdl2-mixer shared library which has timidity synthesizer  already compiled in. So you probably don't need any other timidity package. However the synthesizer needs some set of samples. Therefore you need to install freepats package.

sdl2-mixer should also support FluidSynth. So maybe it's possible to use also other sound sets but so far only freepats was tested.

**Comment by pjasicek** [comment]
Added remarks to README (https://github.com/pjasicek/CaptainClaw/commit/d52acab690648e215be422ff06f0d99eff3b3c73). Closing for now
