### ISSUE TITLE
mlf.wav not found - La Roca level_game crashes

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#23]
![image](https://cloud.githubusercontent.com/assets/10581339/25766282/2b9d8cb8-31fa-11e7-9711-d198e49a5c4e.png)

**Comment by pjasicek** [comment]
Should be fixed with https://github.com/pjasicek/CaptainClaw/commit/c88467a507d3ce0df2a55aa8e5b9c6f047fae41f
