### ISSUE TITLE
Camera not moving down when Claw crouching

### ISSUE THREAD

**Issue by krzema12** [pjasicek/CaptainClaw#25]
After several seconds, the camera should show what's below Claw. It's important for the gameplay because it may provide additional knowledge of the level.

Now, Claw just crouches.

**Comment by pjasicek** [comment]
Thanks for the report, same goes for looking upwards.

**Comment by pjasicek** [comment]
How did the camera return to its original position when its done scrolling in original game ? Did it scroll back or just warped immediately to Claw without any backwards scrolling ? I am because I do not have access to original game at the moment :D

**Comment by cipiricus** [comment]
pjasicek, in original game after you stop pressing up or down button, camera come back to initial position immediatly

**Comment by pjasicek** [comment]
Should be implemented with https://github.com/pjasicek/CaptainClaw/commit/c3a2ef21673e7733f1c6bda6ed5f9ef516b627e1

After 1.5s either after looking up or looking down, the camera moves 400pxs up / down within ~1.3s

**Comment by cipiricus** [comment]
I'm thinking 400pxs is to much, so i maded some modifications of code, not much 
![image](https://cloud.githubusercontent.com/assets/10581339/25855387/b9e88d7c-34db-11e7-8f92-9bdcf18376c3.png)

**Comment by cipiricus** [comment]
And that for looking up, I will try tonight to find how much pixels camera is moving in original game and I will write de modifications 
![image](https://cloud.githubusercontent.com/assets/10581339/25855520/15436886-34dc-11e7-82a4-b8c1130ff210.png)

**Comment by pjasicek** [comment]
I will definitely make this feature configurable (the scroll speed and depth)

**Comment by pjasicek** [comment]
After running original Claw, the look up/down distance is about 200 pixels and the camera returns smoothly (altought faster than looking up/down) to the Claw's position, it does not warp immediately to him.

**Comment by cipiricus** [comment]
So it can remain with 200 pixels? :+1:

**Comment by pjasicek** [comment]
By default I think yes. I will make it configurable though.

**Comment by pjasicek** [comment]
Final implementation in 7aefe5df31e5699faa1378018d661c10aa2285ac

Max look up / down is set to 250px, look up / down is 250px / s, start look up / down time is 1500ms

These values are configurable in config.xml in GlobalOptions
