### ISSUE TITLE
Failed to compile on Ubuntu 16.04.2!!

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#3]
![image](https://cloud.githubusercontent.com/assets/10581339/24932012/443d9fa0-1f18-11e7-9de7-b9086e453a04.png)

How can I fix that?

**Comment by pjasicek** [comment]
Looks like you do not have all required libraries installed. 

Try running:

sudo apt install libsdl2-image-dev

I probably forgot to add this package in installation guide, I will update it

**Comment by cipiricus** [comment]
Thank you! Succesfully compiled. I'm thinking if it possible to compile the game on Raspberry Pi, just curiosity. Anyway the game is in alpha but doesn't matter, I want to thank you once again for this project, you bring back my childhood memories :) :+1:

**Comment by loblik** [comment]
The game should run on any reasonable linux desktop distribution with required dependencies installed. For raspberry pi I think you have two options. You can install all build tools like g++, cmake, make and others and try to compile the project on raspberry itself. If you use raspbian it would be the same procedure like compiling on debian/ubuntu. Although compiling on raspberry will be probably slow.
Second option is to use toolchain for your raspberry distribution and crosscompile the game on your machine. I guess this should also possible as cmake shoud respect CCX and other variables but crosscompiling has not been much tested yet.
