### ISSUE TITLE
Treasures falling through textures and game crashes because physics

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#30]
I descovered two bugs: 
1. All treasures are falling through textures
2. When I try to kill a enemy with Pistol or Magic Claw the game crashes, here is the proof: https://cloud.orange.ro/share/3e2b78cda15d6ff41cff48268b71b3ab09daa7984b474901

**Comment by denispapec** [comment]
Same issues here: 
![coins1](https://cloud.githubusercontent.com/assets/5442891/26176916/a3d15b3e-3b4f-11e7-961a-4b6529798842.png)
![coins2](https://cloud.githubusercontent.com/assets/5442891/26176917/a3de8ae8-3b4f-11e7-94aa-b3ac82fb26aa.png)

**Comment by cipiricus** [comment]
You watched my video proof? :P

**Comment by pjasicek** [comment]
Thanks for the report. Caused most likely by 83c98ccd1be60393714ed3fd35e9f0ca186f7436 or 83a92d42fcf5f0c4b44b77883f4c06daa715403f
