### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by iezed** [pjasicek/CaptainClaw#4]
Hi, I have compiled on ubuntu without error. 
I put the file CLAW.REZ in to Build_Release, but when I run out the binary, I have this message :
ERROR: [VGetRawResourceSize] Could not locate: /states/menu/sounds/menubed.wav in rezArchive: CLAW.REZ
ERROR: [Load] Resource size return -1 => Resource not found. Resource: /states/menu/sounds/menubed.wav
Segmentation fault (core dumped)
Thanks for your works, and sorry for my english.

**Comment by RTheren** [comment]
Works on my end.

From where you have the .REZ file?

**Comment by iezed** [comment]
I get the Claw CD Rip from this link : http://kapitanpazur.piasta.pl/en/downloads.html.

**Comment by RTheren** [comment]
Download the DVD torrent version, that's what works for me.
I think the CD wasn't working for me either

**Comment by iezed** [comment]
Thanks.
