### ISSUE TITLE
Throwing knives

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#46]
The dogs with throwing knives are very fast, is possible to slow down little bit?

**Comment by pjasicek** [comment]
Sure. it is possible. But it gives the game a harder aspect :)

**Comment by pjasicek** [comment]
I added 250ms delay to attacks of the guy who throws knife and 150ms delay to the guy who shoots arrows. 25131cdfe90fefe7105d4b5db5d6999dbdf0f206

**Comment by cipiricus** [comment]
ok...TY :+1:
