### ISSUE TITLE
[Level 4] SteppingStone logic is not implemented

### ISSUE THREAD

**Issue by pjasicek** [pjasicek/CaptainClaw#47]
There are ground at the top of the goo (death tiles) which can be stepped on that disappear for a while after being stepped on and then reappear again

**Comment by pjasicek** [comment]
A bit unlucky situation... Original Claw stopped working on my PC.

There are 4 distinct logics for this::

SteppingStone
SteppingStone2
SteppingStone3
SteppingStone4

I imagine they differ by having different time being off once Claw steps on them, but I cannot be sure.

**Comment by pjasicek** [comment]
I implemented it as such:

When Claw steps on it, there is 150ms delay after which the ground will toggle, then it will stay off for another 500ms.

**Comment by denispapec** [comment]
> I imagine they differ by having different time being off once Claw steps on them, but I cannot be sure.
If i remember correctly, some of them allow big jumps and some of them small jumps.
