### ISSUE TITLE
Roadmap: What's next

### ISSUE THREAD

**Issue by pjasicek** [pjasicek/CaptainClaw#5]
Okay, so today I finished making first level fully functional (atleast to my liking), though there are some little things that should be fixed / implemented in the future, mainly:

- **Sound attentuations** - all sounds have the same origin, there is no mechanism to attentuate sounds ti fit its direction's origin
- **Slowly falling on the edges because of capsule shape** - in original game when Claw went too close to the edge of platform / ground, he did not fall but he went into that ridiculous state where he was wawing his hands as to stop from falling down. I will surely implement this in the future but not now.

Besides this, I am pretty happy with the current result. **So I will now focus on making other levels accessible** ! I am especially looking forward to implementing boss fights - for that I intend to implement some simple LUA scripting hooks.

How I see the project going:

**1.5**: Completely working level 2 with its bossfight
**1.6**.: Levels 3 and 4 - for that I will need to implement some new behaviours, such as ropes (I am getting sick thoughts about how to hack it together like the rest of my physics) and the plant which shoots Claw upwards into the air (for this I will also need to hack my physics system)

After these levels are done, pretty much all mandatory ingame logics will be inplace. After finishing level 4 I intend to focus on optimizing the game for Android (mainly its controls, but also FPS could be higher).

**Comment by cipiricus** [comment]
I hope in near future the bugs of level 2 will be fixed, for example droping through textures

**Comment by pjasicek** [comment]
Yes, I know about it and it is currently my priority. It will certainly be fixed within 2 or 3 days.

If anyone should care as to know why it currently happens: The tile physics is consisting of small rectangles, some are 64x64 pixels, some 20x64 pixels etc. and when several tiles are in one line, there should not be any gap, but since Box2D is not pixel-perfect collision system (none of the physics systems out ther eit), there is a miniature gap causing Claw with his capsule shape sometimes fall through it.

You can view it by console command "physicsdebug on" (console shows after pressing semicolon (";"))

**Comment by pjasicek** [comment]
Dropping through textures should be fixed with https://github.com/pjasicek/CaptainClaw/commit/774218fd00e203ca5bf00ce8734950967fb4742d

**Comment by cipiricus** [comment]
Hi, Falling through textures is fixed, Level 2 works flawless. I'm curious if Box2D can handle some original game physics for example: dropping barrels, dynamite throwing...

**Comment by pjasicek** [comment]
Box2D can handle everything, it is up to me to implement it (e.g. hack it so it works like in original game). Dynamite throwing will stay like it is now for some time, since I find it really fun even though its not exactly as in original game.

**Comment by cipiricus** [comment]
I noticed something weird at some stairs, if you want I can make a video and send link for video

**Comment by pjasicek** [comment]
Im not sure which stairs you mean. Please make a video and file a new issue. Thanks for testing :)

**Comment by cipiricus** [comment]
Magic swords (fire, ice and lightning) will be implemented before or after all maps will be accesible?

**Comment by pjasicek** [comment]
Oh, forgot all about them. I will add them tommorrow as it will be farily easy with current design.

**Comment by pjasicek** [comment]
Fire/Frost/Lightning swords implemented with https://github.com/pjasicek/CaptainClaw/commit/2a878ff1ff27d2dbe307123cc97eeeb67a4805b6

Also magic sword powerups can be manually turned on via console commands:

"firesword"
"frostsword"
"lightningsword"

**Comment by pjasicek** [comment]
Alright, there are only 2 things missing from level 2:

- Rats operating cannons
- Boss fight

Level 1 should be completely implemented as of ambient sounds are implemented.

Once I am done with level 2, I will implement score screen and transitioning between levels.

**Comment by cipiricus** [comment]
In future when the game will more developed I hope that enhancement will be implemented: "in the original Claw game, when a treasure fall into spikes it dessapears something like that happening when treasures fall into lava or tar"

**Comment by pjasicek** [comment]
Yes, sure, these are the little things.

**Comment by pjasicek** [comment]
So right now only LaRaux (Level 2 Boss) is missing from having 2 complete levels.

I assume I will gather myself and do it through following weekend, though last weekend really taxed me (f714339800bd1c4291baa62b6a648e3e51f6fbdc).

After this, jolly good time will most likely follow, since the only important logics in following levels will be Rope and Plant shooting Claw upwards.

**Comment by pjasicek** [comment]
Alright, since 5a943b0f2e355763eef3d6b67fc2a2826d337a8b the first 2 levels are complete along with bossfight ! There are some minor bugs which I deem unsignificant for now.

Time to implement levels 3 & 4 !

**Comment by pjasicek** [comment]
Level 3 is now "playable" with missing 4 or 5 logics. I will work on it this week and hopefully finish it within 5-6 days. Level 4 will then be a breeze !

**Comment by pjasicek** [comment]
Level 3 is complete ! Only score screen is missing, which should be easy.

**Comment by pjasicek** [comment]
Level 4 is in place (with missing SteppingStone and flower which is shooting Claw up) !

41f941996ac8ed61c91dc6727af8ff469fea0e34

**Comment by pjasicek** [comment]
After finishing Level 4 I will most likely focus my efforts on creating .deb and .rpm packages for Linux distributions. Then I will lay my effort on porting it to Android (huge amount of work was already done by @loblik ).

**Comment by denispapec** [comment]
If nothing else, i can jump in with creation of AUR package at least, if you don't mind :).

**Comment by pjasicek** [comment]
Today I was able to finish playing of all 4 levels consecutively ! My second big milestone which was planned for 1.6. is finished.

Now I will polish the game as much as I can (adding additional misc features) and I will make the Linux packages.

**Comment by cipiricus** [comment]
I saw in original Claw game the level 4 boss Katherine is jumping over Claw, that is possible with only boss logic or it needed Box2D implementation?

**Comment by pjasicek** [comment]
It is not limitation of Box2D, the logic is just no implemented by me. Both bosses have the same logic - they just go after claw and do melee attacks, nothing else. I will implement it like it was in original game in future I think.

**Comment by cipiricus** [comment]
aah, ok..I'm thinking if Box2D needed some adjustements for that

**Comment by pjasicek** [comment]
I am taking a short break from developing CC, I assume it will be matter of a few weeks before I return.

**Comment by pjasicek** [comment]
Closing this since mostly everything described in the first post is done.
