### ISSUE TITLE
Crashing on green tar

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#51]
The game is crashing when Claw fall into shitty green tar on level 4 
![image](https://cloud.githubusercontent.com/assets/10581339/26323821/05cda102-3f39-11e7-9a36-2243099cb2bc.png)

**Comment by pjasicek** [comment]
Thanks for the report. It is fixed on my machine, but I will commit it once I finish the SpringBoard logic, which should be today.

**Comment by pjasicek** [comment]
Should be fixed with 99824e4503a6e37307d3dc82e7e7ab360d0bb8c3
