### ISSUE TITLE
Actor voices

### ISSUE THREAD

**Issue by denispapec** [pjasicek/CaptainClaw#52]
Actors should have their own voice. At this moment Cutthroat and Robber Thief are using same voices as Officer and Soldier, and at least on level 3 and 4 there is missing occasional characters voices, like actors burps :)

**Comment by pjasicek** [comment]
Yea, I am sadly aware of that. I cannot fight correct voices for death sounds for level 3/4 enemies anywhere as I am unable to play the original game. I will probably have to watch some videos.

As to the occasional voices, I will probably implement it once I finish level 4, since it is additional feature which is not that crucial at this moment.

Thanks for the report as always :)

**Comment by jan-kleks** [comment]
@pjasicek Try running the game through [PCem](http://pcem-emulator.co.uk) if you have any issues.

**Comment by pjasicek** [comment]
@jan-kleks what exactly is the purpose behind running it on PCem ?

**Comment by pjasicek** [comment]
Regarding this issue - This should be solved by adding new EnemyAIComponent to enemies - once they enter the defined area for sound trigger, it should roll a dice whether it should play some enemy random voice or something.

Also the same should go for Claw killing enemies - he has a chance to generate a sound when he kills enemy, like "Hah ! Take that !" and so on.

**Comment by pjasicek** [comment]
After a bit of investigation, enemies in Level 1 (and I would assume it is the same in other levels), do emotes under 2 circumstances:

1) When they are patrolling and are in the idle animation - they look around on the spot. When Claw is near when they transition into this state, they have a chance (I guess in ~75ish % range) to do voice emote.

2) When Claw gets into their melee (for Officer) or ranged (for Soldier) agro range - they have a chance (I guess in ~33ish % range) to do aggressive voice emote.

In both cases they display the exclamation mark - the same one which is displayed above Claw when he does voice emote.

So no new state is necessary, just add it to existing states (attack and patrol).

**Comment by pjasicek** [comment]
Level 1 enemies (soldier and officer) have this feature implemented since https://github.com/pjasicek/CaptainClaw/commit/8efb990065a540a35af182a42af819864fa0a1e4

**Comment by pjasicek** [comment]
Level 2 enemies also have speeches since https://github.com/pjasicek/CaptainClaw/commit/83eb60e2bff8d01dd6948a90b41da7ca4be253d0

**Comment by pjasicek** [comment]
Level 5 and 6 enemies have speeches also. Only level 3 and 4 are missing.

**Comment by cipiricus** [comment]
On level 3 the robber thief death sound is similar with la roca guardian, and at level 4 both type of enemies, robber thieves and cutthroats has death sound similar with enemies from la roca and battlements

**Comment by pjasicek** [comment]
Fixed with https://github.com/pjasicek/CaptainClaw/commit/4dba4b87ddb5ea082333ec49825cbc3eec424c84
