### ISSUE TITLE
Plant jump

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#54]
I think the throwing up of Claw by plants must be slightly increased little bit, if is possible...
![image](https://cloud.githubusercontent.com/assets/10581339/26327379/e4c39caa-3f47-11e7-8459-61468f2cdb9d.png)

**Comment by denispapec** [comment]
Indeed  :)
![jump](https://cloud.githubusercontent.com/assets/5442891/26327494/9755b4cc-3f37-11e7-8469-3f4cf1e561ef.gif)

**Comment by pjasicek** [comment]
Alright, I will get on it tomorrow and make it configurable, thanks for the report guys

**Comment by pjasicek** [comment]
I just found out that plants have property which says how far up in the air it springs.
