### ISSUE TITLE
New Game bug

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#56]
When I use New Game option, Claw doesn't start from begining..
https://cloud.orange.ro/share/93b23c2bde2700c61cff48268b71b3ab09daa7984b474901

**Comment by pjasicek** [comment]
Should be fixes. I accidentally committed helper file startup_commands.txt where I specified a postion with which Claw starts every level.

**Comment by cipiricus** [comment]
Yep, is fixed! Thank a lot! :+1:
