### ISSUE TITLE
Get in touch with The Claw Recluse community

### ISSUE THREAD

**Issue by jan-kleks** [pjasicek/CaptainClaw#62]
Hello!

Thank you for this awesome project!!!

You should definitely get in touch with [The Claw Recluse Polish community](http://www.kapitanpazur.piasta.pl/en/), and write there about your project (an English forum section is available too). You might find there people with experience in reverse engineering Claw who might be willing to help. For example, you can find there the CrazyHook mod which adds support for advanced level scripting using the Lua language, and many people were trying to create their own reimplementations of the game (with varying degrees of success).

BTW, Claw was extremely popular in Poland, we even had our own [official enhanced version of the game released in 2006 ](http://www.empik.com/kapitan-pazur-drapiezna-edycja-takarajimasha-group,2416034,multimedia-p) with additional levels (what is interesting, they were created by The Claw Recluse team!).

**Comment by pjasicek** [comment]
Hi

Thank you for the kind words !

Thanks for the suggestion, I will get in touch with the community once I am ready to continue working on this project (I am taking a few weeks off). Regarding reverse engineering Monolith's file formats (REZ, WWD, PID, PAL, ...) - mostly everything is done, it is encapsulated within the "libwap" library project (I owe big thanks to guys kijanek6 and KubusPL I believe who have done tremendous work on Monolith's file formats before me).

**Comment by jan-kleks** [comment]
Actually, KubusPL is a prominent member of The Claw Recluse community, so here you go. :P 

The community could also help you with **thoroughly** testing your reimplementation. Of course, the most important thing is to make your version fully playable, but **maybe in the future it would be even possible to use your version against the original release for speed-running** (unfortunately, on modern systems, original Claw is running either too fast or too slow). That would've been beyond awesome!

**Comment by jan-kleks** [comment]
I can see that your project has already been mentioned as "the future of Claw development" at The Claw Recluse. 

So you can already introduce your project and yourself [here](http://www.clawforum.fora.pl/glowna-dyskusja,25/). It's a general section of the Polish part of the site, well, maybe it would be better to post there after all (even in English), it's more often visited than the English section.

**Comment by pjasicek** [comment]
http://www.clawforum.fora.pl/english-zone,9/captainclaw-c-open-source-reimplementation-github,5095.html

Done !
