### ISSUE TITLE
Level start bug

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#74]
There is a level bug from last commit...
![captura de ecran din 2017-07-13 21-23-07](https://user-images.githubusercontent.com/10581339/28181576-cbb55cce-6811-11e7-8da2-2c1949b77aa9.png)
![captura de ecran din 2017-07-13 21-23-33](https://user-images.githubusercontent.com/10581339/28181573-cbaa541e-6811-11e7-8098-0031f15be038.png)
![captura de ecran din 2017-07-13 21-24-03](https://user-images.githubusercontent.com/10581339/28181572-cbaa2390-6811-11e7-977a-7308c5e5c6eb.png)
![captura de ecran din 2017-07-13 21-24-22](https://user-images.githubusercontent.com/10581339/28181574-cbae0e92-6811-11e7-9e37-d4b82ccc2af0.png)

**Comment by pjasicek** [comment]
Sorry about that. Trying a new source control tool (SourceTree) and its a bit tricky.
