### ISSUE TITLE
Claw get stuck

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#76]
Claw get stuck when ducks on edge of terrain, only solution to escape is Claw's death

![image](https://user-images.githubusercontent.com/10581339/28237846-bf8b9ef0-6950-11e7-8853-9f23c64b4ddb.png)

**Comment by pjasicek** [comment]
Thanks for report. This is the same issue as #32 - this is a bug in physics which is hard to fix. Once I manage to merge all continuous tiles, this will be resolved.
