### ISSUE TITLE
Enemy attack AI states are not flexible

### ISSUE THREAD

**Issue by pjasicek** [pjasicek/CaptainClaw#8]
Right now enemy needs to have a new subclass for each possible attack state (stand-attack, stand-shoot, duck-attack, duck-shoot) just because of different agro fixtures attached to these states.

The code itself is almost exactly the same for each *AttackStateAIComponent, so to avoid code repetition, refactor the approach. Solution:

1. Have only 1 class of attack state - AttackStateAIComponent
2. In BaseAIStateComponent add m_StatePriority property - for example, stand-shooting should have higher priority than duck-shooting. Enemy should then duck-shoot only when enemy is also ducking, not when he is standing
3. In BaseAIStateComponent create a pure virtual method - bool VCanEnterState() - use this for determining whether enemy can enter requested state or not. For example, for attack state enemy can only enter the state if there are enemies in his agro range. For patrol state, enemy can always enter patrol state (if he is not dying).
4. When picking the next state, just loop through all BaseAIStateComponents and cann VCanEnter state and from that, pick the state with highest priority.
5. Enemy agro fixtures have to be embedded into the AttackAIComponents themselves.
6. I will probably need some kind of observer again for observing the actors (Claw) who will enter the agro range

Right now I will probably not implement it and stick with the rather more inflexible design as it is right now (I will just add 2 more states for duck-attack and duck-shoot and handle the state transition). But I want this to be visible for me here as a reminder as something I will need to fix in a future.

**Comment by cipiricus** [comment]
Will be nice if in near future enemy can atack at duck like at original game ;)

**Comment by pjasicek** [comment]
They will definitely be able to do that, but the architecture from the code point of view can be improved so it is easily extended with new attack states, e.g. jump-attack or something like that.

I plan on implementing duck-attack states today or tomorrow.

**Comment by cipiricus** [comment]
Ok...when duck-attack will be finished, I will test the game :) :+1:

**Comment by pjasicek** [comment]
Should be implemented with https://github.com/pjasicek/CaptainClaw/commit/731aaa2eef16741aa150e6c1571fe9d727c1c1d8

I also refactored nearly whole enemy actor / enemy state component system so that it is easily enough extendable for my purposes.
