### ISSUE TITLE
Claw's jump

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#81]
In level 6 there some platforms on the windows, Claw can't jump on them if is not catnaped

**Comment by pjasicek** [comment]
You are right. In original game, Claw runs slower by default and jumps a bit higher. In my implementation right now, Claw runs faster by default and jumps not so high.

**Comment by pjasicek** [comment]
Fixed with https://github.com/pjasicek/CaptainClaw/commit/a97e66cfa4b62881087a1b5e4589c96b58455abf
