### ISSUE TITLE
[Level 6] After losing life immediately after save point 1, platform doesn't move or moves without Claw (and doesn't return)

### ISSUE THREAD

**Issue by denispapec** [pjasicek/CaptainClaw#88]
Steps to reproduce:
1. Load level from beginning or from save point 1
2. Reach end of path with that platform (see on images)

![screenshot-2017-08-15_23 35 47](https://user-images.githubusercontent.com/5442891/29339621-0009ab4a-8213-11e7-87de-9d27014c9984.png)
![screenshot-2017-08-15_23 36 14](https://user-images.githubusercontent.com/5442891/29339625-02d44934-8213-11e7-8d6b-80ae5a0ecf28.png)

**Comment by pjasicek** [comment]
Fixed. I hope this fix did not introduce any new bugs.
