### ISSUE TITLE
[Level 6] Moonwalking

### ISSUE THREAD

**Issue by denispapec** [pjasicek/CaptainClaw#89]
![ezgif com-crop](https://user-images.githubusercontent.com/5442891/29340103-4f0598ec-8215-11e7-8d78-f41483f68915.gif)

**Comment by cipiricus** [comment]
I know about bug, I think is related with physics :joy:

**Comment by pjasicek** [comment]
Thanks for report as always. I think I would never stumble upon bugs like this 😄 

Should be fixed. Bug was in Rope which handled Claw's turning left/right.
