### ISSUE TITLE
Picking powerup should change background music for the duration

### ISSUE THREAD

**Issue by pjasicek** [pjasicek/CaptainClaw#9]
When Claw picks any powerup (Catnip, Fire Sword, invisibility...) the background music should change to /GAME/MUSIC/POWERUP.XMI.

When powerup runs out, the music should the return back to the original level music, but not to the beginning - to the time when it was when powerup music interrupted it

**Comment by pjasicek** [comment]
SDL_Mixer is not supporting setting music playback position, so setting level music back to when it was interrupted is at the moment not possible. Also there is the problem with music running in another process.

So the question is whether to support this feature and when the powerup ends just play the level music from the beginning or whether to skip this entirely.

**Comment by denispapec** [comment]
> When Claw picks any powerup (Catnip, Fire Sword, invisibility...) the background music should change to /GAME/MUSIC/POWERUP.XMI.

So that means we should be hearing background music already? 
If so, on Arch Linux (SDL_Mixer version 2.0.1-1) i can hear any sound during first and second level except background music.

Thanks for bringing this awesome game also to Linux! :)

**Comment by pjasicek** [comment]
Oh. Yes, playing background music for all levels is already implemented, my main development machine is on Windows though, so I can't easily test it on Linux distributions. When my colleague, Pavel, ported this to Android, there was also issue that the music was not playing - it was caused by missing MIDI instrumental files.

You should be able to hear the music when you install Timidity - https://wiki.archlinux.org/index.php/timidity

If this will not work, please create a bug for it, but I am quite sure that properly installing timidity will resolve it.

**Comment by pjasicek** [comment]
Playing powerup music when Claw has powerup is implemented with https://github.com/pjasicek/CaptainClaw/commit/681385bfae3f84acbba95e98822758db08d2d3a5

Closing and creating a new bug regarding the level music not playing from the point when it was interrupted.
