### ISSUE TITLE
Dynamite bug

### ISSUE THREAD

**Issue by denispapec** [pjasicek/CaptainClaw#94]
Dynamite behaviour should be that it lands in front of Claw

![bombsaway](https://user-images.githubusercontent.com/5442891/29436179-4b597342-83a2-11e7-8004-2bc372369b59.gif)

**Comment by pjasicek** [comment]
same as #101 - way too much effort to implement it now with current design

**Comment by pjasicek** [comment]
Nevermind, this feature is not that much effort for me. I will most likely implement it sometime this week. But regarding the barrels... im not sure.

**Comment by pjasicek** [comment]
Implemented with following commits:

https://github.com/pjasicek/CaptainClaw/commit/4740c95133afbe0edcaf57a7eefa2bd0280a52c0
https://github.com/pjasicek/CaptainClaw/commit/5d29e97436f4049c62066980eb9a0d7d4064eb1d

If you want some tweaks or something is not right, create another issue please
