### ISSUE TITLE
Damage bug on contact with actors

### ISSUE THREAD

**Issue by denispapec** [pjasicek/CaptainClaw#95]
Damage should be applied only when actors are in attack mode.

![damageoncontact](https://user-images.githubusercontent.com/5442891/29436254-93ef9b04-83a2-11e7-8a4a-704a9653d8c2.gif)

**Comment by jstasiak** [comment]
Same issue here, you beat me to reporting it. :)

**Comment by denispapec** [comment]
:P

**Comment by pjasicek** [comment]
And here I thought this was original behaviour 😄

**Comment by pjasicek** [comment]
Try it with https://github.com/pjasicek/CaptainClaw/commit/8e2041d9a407a656da79fdbdb4f933904a5f1a79 please

It should be fixed but I may have missed something
